'use strict';var React,ReactDOM,React__default,ReactDOM__default,shallowEqual,hotReplacementRender$1;function _interopDefaultLegacy(a){return a&&"object"==typeof a&&"default"in a?a:{default:a}}Object.defineProperty(exports,"__esModule",{value:!0});React=require("react");ReactDOM=require("react-dom");React__default=_interopDefaultLegacy(React);ReactDOM__default=_interopDefaultLegacy(ReactDOM);shallowEqual=Object.is;
let hoistBlackList={$$typeof:1,render:1,compare:1,type:1,childContextTypes:1,contextType:1,contextTypes:1,defaultProps:1,getDefaultProps:1,getDerivedStateFromError:1,getDerivedStateFromProps:1,mixins:1,propTypes:1};function hoistNonReactStatic(a,b){let c=Object.getOwnPropertyNames(Object.getPrototypeOf(a));Object.getOwnPropertyNames(a).forEach(f=>{hoistBlackList[f]||-1!==c.indexOf(f)||Object.defineProperty(b,f,Object.getOwnPropertyDescriptor(a,f))})}
let isCompositeComponent=a=>"function"==typeof a,isReloadableComponent=a=>"function"==typeof a||"object"==typeof a,getComponentDisplayName=a=>(a=a.displayName||a.name)&&"ReactComponent"!==a?a:"Component",reactLifeCycleMountMethods=["componentWillMount","componentDidMount"];
function isReactClass(a){return!(!a.prototype||!(React__default.default.Component.prototype.isPrototypeOf(a.prototype)||a.prototype.isReactComponent||a.prototype.componentWillMount||a.prototype.componentWillUnmount||a.prototype.componentDidMount||a.prototype.componentDidUnmount||a.prototype.render))}function isReactClassInstance(a){return a&&isReactClass({prototype:Object.getPrototypeOf(a)})}
let ContextType=React__default.default.createContext?React__default.default.createContext():null,ConsumerType=ContextType&&ContextType.Consumer.$$typeof,ProviderType=ContextType&&ContextType.Provider.$$typeof,MemoType=React__default.default.memo&&React__default.default.memo(()=>null).$$typeof,LazyType=React__default.default.lazy&&React__default.default.lazy(()=>null).$$typeof,ForwardType=React__default.default.forwardRef&&React__default.default.forwardRef(()=>null).$$typeof,isContextConsumer=({type:a})=>
a&&"object"==typeof a&&"$$typeof"in a&&a.$$typeof===ConsumerType&&ConsumerType,isContextProvider=({type:a})=>a&&"object"==typeof a&&"$$typeof"in a&&a.$$typeof===ProviderType&&ProviderType,isMemoType=({type:a})=>a&&"object"==typeof a&&"$$typeof"in a&&a.$$typeof===MemoType&&MemoType,isLazyType=({type:a})=>a&&"object"==typeof a&&"$$typeof"in a&&a.$$typeof===LazyType&&LazyType,isForwardType=({type:a})=>a&&"object"==typeof a&&"$$typeof"in a&&a.$$typeof===ForwardType&&ForwardType,isContextType=a=>isContextConsumer(a)||
isContextProvider(a),getElementType=a=>{let b={type:a};return isContextConsumer(b)?"Consumer":isContextProvider(b)?"Provider":isLazyType(b)?"Lazy":isMemoType(b)?"Memo":isForwardType(b)?"Forward":isReactClass(a)?"Class":"function"==typeof b?"FC":"unknown"},getContextProvider=a=>a&&a._context,configuration={logLevel:"error",pureSFC:!0,pureRender:!0,allowSFC:!0,reloadHooks:!0,reloadLifeCycleHooks:!1,reloadHooksOnBodyChange:!0,disableHotRenderer:!1,integratedComparator:!1,integratedResolver:!1,disableHotRendererWhenInjected:!0,
showReactDomPatchNotification:!0,onComponentRegister:!1,onComponentCreate:!1,ignoreSFC:!1,ignoreSFCWhenInjected:!0,ignoreComponents:!1,errorReporter:void 0,ErrorOverlay:void 0,trackTailUpdates:!0,wrapLazy:!0,IS_REACT_MERGE_ENABLED:!1},internalConfiguration={disableProxyCreation:!1},setConfiguration=a=>{for(let b in a)a.hasOwnProperty(b)&&(configuration[b]=a[b])},logger={debug(...a){-1!==["debug"].indexOf(configuration.logLevel)&&console.debug(...a)},log(...a){-1!==["debug","log"].indexOf(configuration.logLevel)&&
console.log(...a)},warn(...a){-1!==["debug","log","warn"].indexOf(configuration.logLevel)&&console.warn(...a)},error(...a){-1!==["debug","log","warn","error"].indexOf(configuration.logLevel)&&console.error(...a)}};function safeReactConstructor(a,b){try{return b?new a(b.props,b.context):new a({},{})}catch(c){}return null}function isNativeFunction(a){return"function"==typeof a&&0<a.toString().indexOf("[native code]")}
let identity=a=>a,indirectEval=eval,proxyClassCreator=function(){try{return indirectEval("class Test {}"),!0}catch(a){return!1}}()?(a,b)=>indirectEval(`\n(function(InitialParent, postConstructionAction) {\n  return class ${a.name||"HotComponent"} extends InitialParent {\n    /*\n     ! THIS IS NOT YOUR COMPONENT !\n     !  THIS IS REACT-HOT-LOADER  !\n  \n     this is a "${a.name}" component, patched by React-Hot-Loader\n     Sorry, but the real class code was hidden behind this facade\n     Please refer to https://github.com/gaearon/react-hot-loader for details...\n    */    \n    \n    constructor(props, context) {\n      super(props, context)\n      postConstructionAction.call(this)\n    }\n  }\n})\n`)(a,
b):function(a,b){function c(c,e){a.call(this,c,e);b.call(this)}return c.prototype=Object.create(a.prototype),Object.setPrototypeOf(c,a),c};function deepPrototypeUpdate(a,b){let c=Object.getPrototypeOf(a),f=Object.getPrototypeOf(b);c&&f&&f!==c&&deepPrototypeUpdate(c,f);b.prototype&&b.prototype!==a.prototype&&(a.prototype=b.prototype)}function safeDefineProperty(a,b,c){try{Object.defineProperty(a,b,c)}catch(f){logger.warn("Error while wrapping",b," -> ",f)}}
let PREFIX="__reactstandin__",PROXY_KEY=`${PREFIX}key`,GENERATION=`${PREFIX}proxyGeneration`,REGENERATE_METHOD=`${PREFIX}regenerateByEval`,UNWRAP_PROXY=`${PREFIX}getCurrent`,CACHED_RESULT=`${PREFIX}cachedResult`,PROXY_IS_MOUNTED=`${PREFIX}isMounted`,RENDERED_GENERATION="REACT_HOT_LOADER_RENDERED_GENERATION",RESERVED_STATICS=["length","displayName","name","arguments","caller","prototype","toString","valueOf","isStatelessFunctionalProxy",PROXY_KEY,UNWRAP_PROXY];
function transferStaticProps(a,b,c,f){return Object.getOwnPropertyNames(a).forEach(c=>{if(-1===RESERVED_STATICS.indexOf(c)){var e=Object.getOwnPropertyDescriptor(a,c);shallowEqual(e,b[c])||safeDefineProperty(f,c,e)}}),Object.getOwnPropertyNames(f).forEach(e=>{if(-1===RESERVED_STATICS.indexOf(e)){var d=c&&Object.getOwnPropertyDescriptor(a,e),l=b[e];if(d&&l&&!shallowEqual(l,d))return void safeDefineProperty(f,e,d);if(d&&!l)return void safeDefineProperty(a,e,d);d={...Object.getOwnPropertyDescriptor(f,
e),configurable:!0};b[e]=d;safeDefineProperty(a,e,d)}}),Object.getOwnPropertyNames(a).forEach(e=>{var d,l;-1!==RESERVED_STATICS.indexOf(e)||f.hasOwnProperty(e)||(d=Object.getOwnPropertyDescriptor(a,e))&&!d.configurable||(d=c&&Object.getOwnPropertyDescriptor(c,e),l=b[e],d&&l&&!shallowEqual(l,d)||safeDefineProperty(a,e,{value:void 0}))}),b}
function mergeComponents(a,b,c,f,e){let d={};try{let h=safeReactConstructor(b,f);try{deepPrototypeUpdate(c,b)}catch(n){}let g=safeReactConstructor(a,f);if(!h||!g)return d;b={...g,...h};let t=g[REGENERATE_METHOD],m=(l=Object.getPrototypeOf(a.prototype),[...Object.getOwnPropertyNames(l),...Object.getOwnPropertySymbols(l)]);Object.keys(b).forEach(b=>{var c,f,l,n;if(0!==b.indexOf(PREFIX)&&(c=h[b],f=g[b],c)){if(isNativeFunction(c)||isNativeFunction(f))return l=c.length===f.length,n=0<=m.indexOf(b)||a.prototype[b],
void(!l&&f||!n?logger.warn("React Hot Loader:","Updated class ",a.name,"contains native or bound function ",b,c,". Unable to reproduce, use arrow functions instead.",`(arity: ${c.length}/${f.length}, proto: ${n?"yes":"no"}`):t?d[b]=`Object.getPrototypeOf(this)['${b}'].bind(this)`:logger.warn("React Hot Loader:,","Non-controlled class",a.name,"contains a new native or bound function ",b,c,". Unable to reproduce"));l=String(c);n=e[b];let h=0<=l.indexOf("=>"),g=0<=l.indexOf("function")||h,k=0<=l.indexOf("this");
(l!==String(f)||n&&l!==String(n)||h&&k)&&(t?d[b]=c:g?logger.warn("React Hot Loader:"," Updated class ",a.name,"had different code for",b,c,". Unable to reproduce. Regeneration support needed."):d[b]=c)}})}catch(h){logger.warn("React Hot Loader:",h)}var l;return d}
function inject(a,b,c){if(a[GENERATION]!==b){let f=!!a[REGENERATE_METHOD];Object.keys(c).forEach(b=>{try{if(f){let e=String(c[b]).match(/_this([\d]+)/gi)||[];a[REGENERATE_METHOD](b,`(function REACT_HOT_LOADER_SANDBOX () {\n          var _this  = this; // common babel transpile\n          ${e.map(a=>`var ${a} = this;`)}\n\n          return ${c[b]};\n          }).call(this)`)}else a[b]=c[b]}catch(d){logger.warn("React Hot Loader: Failed to regenerate method ",b," of class ",a),logger.warn("got error",
d)}});a[GENERATION]=b}}
let has=Object.prototype.hasOwnProperty,proxies=new WeakMap,blackListedClassMembers="constructor render componentWillMount componentDidMount componentDidCatch componentWillReceiveProps componentWillUnmount hotComponentRender getInitialState getDefaultProps".split(" "),defaultRenderOptions={componentWillRender:identity,componentDidUpdate:a=>a,componentDidRender:a=>a},filteredPrototypeMethods=a=>Object.getOwnPropertyNames(a).filter(b=>{let c=Object.getOwnPropertyDescriptor(a,b);return c&&0!==b.indexOf(PREFIX)&&
0>blackListedClassMembers.indexOf(b)&&"function"==typeof c.value}),setSFPFlag=(a,b)=>safeDefineProperty(a,"isStatelessFunctionalProxy",{configurable:!1,writable:!1,enumerable:!1,value:b}),copyMethodDescriptors=(a,b)=>(b&&(Object.getOwnPropertyNames(b).forEach(c=>safeDefineProperty(a,c,Object.getOwnPropertyDescriptor(b,c))),safeDefineProperty(a,"toString",{configurable:!0,writable:!1,enumerable:!1,value:function(){return String(b)}})),a),knownClassComponents=[],forEachKnownClass=a=>knownClassComponents.forEach(a);
function createClassProxy(a,b,c={}){function f(){if(this[GENERATION]=0,B=this,x){let a=x;x=null;a()}inject(this,v,w)}function e(b,c=identity){return copyMethodDescriptors(function(...a){return this&&inject(this,v,w),c(this),!y&&r.prototype[b]&&r.prototype[b].apply(this,a)},a.prototype&&a.prototype[b])}function d(){if(m.componentWillRender(this),this&&inject(this,v,w),has.call(this,CACHED_RESULT)){var a=this[CACHED_RESULT];delete this[CACHED_RESULT]}else if(y)a=r(this.props,this.context);else{if((a=
r.prototype.render||this.render)===h)throw Error("React-Hot-Loader: you are trying to render Component without .render method");a=a.apply(this,arguments)}return m.componentDidRender.call(this,a)}function l(){m.componentWillRender(this);this&&inject(this,v,w)}function h(...a){return m.componentWillRender(this),d.call(this,...a)}function g(){return r}function t(b){if("function"!=typeof b)throw Error("Expected a constructor.");if(b===r||proxies.get(b))return!1;y=!isReactClass(b);proxies.set(b,p);v++;
var c=r;r=b;let e=getComponentDisplayName(r);return safeDefineProperty(k,"displayName",{configurable:!0,writable:!1,enumerable:!0,value:e}),q&&safeDefineProperty(q,"name",{value:e}),u=transferStaticProps(k,u,c,b),!y&&q&&(c=()=>{!function(a,b){try{let c=Object.getPrototypeOf(a.prototype),e=b.prototype;reactLifeCycleMountMethods.forEach(b=>{a:{var f=Object.getOwnPropertyDescriptor(c,b)||{value:c[b]};var d=Object.getOwnPropertyDescriptor(e,b)||{value:e[b]};for(let a in f)if(String(f[a])!==String(d[a])){f=
!1;break a}f=!0}f||logger.warn("React Hot Loader:","You did update",a.name,"s lifecycle method",b,". Unable to repeat")})}catch(G){}}(q,b);1<v&&(getElementCloseHook(q),filteredPrototypeMethods(q.prototype).forEach(a=>{has.call(b.prototype,a)||delete q.prototype[a]}));Object.setPrototypeOf(q.prototype,b.prototype);z(q,b.prototype);1<v&&(w=mergeComponents(q,b,a,B,w),getElementComparisonHook(q))},0<A?c():x=c),!0}let m={...defaultRenderOptions,...c},n={...configuration,...c.proxy};if(c=proxies.get(a))return c;
let r,k,p,u={},w={},v=0,x=null,A=0,y=!isReactClass(a),B=null,C=a=>filteredPrototypeMethods(a).reduce((b,c)=>{var e;return b[c]=(e=a[c],copyMethodDescriptors(function(...a){return e.apply(this,a)},e)),b},{}),D=e("componentDidMount",a=>{a[PROXY_IS_MOUNTED]=!0;a[RENDERED_GENERATION]=get();A++}),E=e("componentDidUpdate",m.componentDidUpdate),F=e("componentWillUnmount",a=>{a[PROXY_IS_MOUNTED]=!1;A--}),z=(a,b={})=>{((a,b)=>{Object.keys(b).forEach(c=>safeDefineProperty(a.prototype,c,{configurable:!0,writable:!0,
enumerable:!1,value:b[c]}))})(a,{...C(b),...n.pureRender?{}:{render:h},hotComponentRender:d,hotComponentUpdate:l,componentDidMount:D,componentDidUpdate:E,componentWillUnmount:F})},q=null;return y?n.allowSFC?k=function(a,b){let c=r(a,b);return isReactClassInstance(c)?(q=null,transferStaticProps(k,u,null,r),c):n.pureSFC&&!r.contextTypes?(k.isStatelessFunctionalProxy||setSFPFlag(k,!0),m.componentDidRender(c)):(setSFPFlag(k,!1),n.pureRender=!1,q=proxyClassCreator(React.Component,f),z(q),(a=new q(a,b))[CACHED_RESULT]=
c,a)}:(n.pureRender=!1,q=proxyClassCreator(React.Component,f),z(q),k=q):(q=proxyClassCreator(a,f),z(q,a.prototype),knownClassComponents.push(q),k=q),safeDefineProperty(k,UNWRAP_PROXY,{configurable:!1,writable:!1,enumerable:!1,value:g}),safeDefineProperty(k,PROXY_KEY,{configurable:!1,writable:!1,enumerable:!1,value:b}),safeDefineProperty(k,"toString",{configurable:!0,writable:!1,enumerable:!1,value:function(){return String(r)}}),t(a),p={get:function(){return k},update:t,dereference:()=>{proxies.delete(a);
proxies.delete(k);proxies.delete(r)},getCurrent:()=>r},proxies.set(a,p),proxies.set(k,p),safeDefineProperty(p,UNWRAP_PROXY,{configurable:!1,writable:!1,enumerable:!1,value:g}),p}
let generation=1,hotComparisonCounter=0,hotComparisonRuns=0,hotReplacementGeneration=0,nullFunction=()=>({}),onHotComparisonOpen=nullFunction,onHotComparisonElement=nullFunction,onHotComparisonClose=nullFunction,getElementComparisonHook=a=>onHotComparisonElement(a),getElementCloseHook=a=>onHotComparisonClose(a),hotComparisonOpen=()=>0<hotComparisonCounter&&0<hotComparisonRuns&&0<hotReplacementGeneration,decrementHot=()=>{hotComparisonCounter--;hotComparisonCounter||(forEachKnownClass(onHotComparisonClose),
hotComparisonRuns++)},enterHotUpdate=()=>{Promise.resolve((hotComparisonCounter||(forEachKnownClass(onHotComparisonElement),onHotComparisonOpen()),void hotComparisonCounter++)).then(()=>setTimeout(decrementHot,0))},increment=()=>(enterHotUpdate(),generation++),get=()=>generation,getHotGeneration=()=>hotReplacementGeneration,UNDEFINED_NAMES={Unknown:!0,Component:!0},areNamesEqual=(a,b)=>a===b||UNDEFINED_NAMES[a]&&UNDEFINED_NAMES[b],isFunctional=a=>"function"==typeof a,getTypeOf=a=>isReactClass(a)?
"ReactComponent":isFunctional(a)?"StatelessFunctional":"Fragment";function clearStringFast(a){return 12>a.length?a:` ${a}`.slice(1)}
let haveTextSimilarity=(a,b)=>a===b||distance(clearStringFast(a),clearStringFast(b))<.2*a.length,getBaseProto=a=>a.prototype.hotComponentRender?Object.getPrototypeOf(a.prototype):a.prototype,areSwappable=(a,b)=>{if(getIdByType(b)&&getIdByType(a)===getIdByType(b))return!0;if(getTypeOf(a)!==getTypeOf(b))return!1;if(isReactClass(a))return areNamesEqual(getComponentDisplayName(a),getComponentDisplayName(b))&&((a,b)=>{let c=getBaseProto(a),f=getBaseProto(b),l=0,h=0,g=0;return Object.getOwnPropertyNames(c).forEach(a=>
{var b=Object.getOwnPropertyDescriptor(c,a);b=b&&(b.value||b.get||b.set);var e=(e=Object.getOwnPropertyDescriptor(f,a))&&(e.value||e.get||e.set);"function"==typeof b&&"constructor"!==a&&(g++,haveTextSimilarity(String(b),String(e))?l++:(h++,"render"===a&&h++))}),0<l&&1>=h||0===g})(a,b);if(isFunctional(a)){let c=getComponentDisplayName(a);return!!areNamesEqual(c,getComponentDisplayName(b))&&("Component"!==c||haveTextSimilarity(String(a),String(b)))}return!1};
function merge(...a){let b={};for(let c of a)if(c instanceof Array)b instanceof Array||(b=[]),b=[...b,...c];else if(c instanceof Object)for(let f of Object.keys(c))(a=c[f])instanceof Object&&f in b&&(a=merge(b[f],a)),b={...b,[f]:a};return b}
let signatures,proxiesByID,blackListedProxies,registeredComponents,idsByType,componentOptions,elementCount=0,renderOptions={},getIdByType=a=>idsByType.get(a),getProxyById=a=>proxiesByID[a],getProxyByType=a=>getProxyById(getIdByType(a)),registerComponent=a=>registeredComponents.set(a,1),isRegisteredComponent=a=>registeredComponents.has(a),updateFunctionProxyById=(a,b,c)=>(idsByType.set(b,a),proxiesByID[a]||(proxiesByID[a]=b),c(proxiesByID[a],b),proxiesByID[a]),updateProxyById=(a,b,c={})=>a?(idsByType.set(b,
a),proxiesByID[a]?proxiesByID[a].update(b)&&hotReplacementGeneration++:proxiesByID[a]=createClassProxy(b,a,merge({},renderOptions,{proxy:componentOptions.get(b)||{}},c)),proxiesByID[a]):null,isColdType=a=>blackListedProxies.has(a),isTypeBlacklisted=a=>isColdType(a)||isCompositeComponent(a)&&(configuration.ignoreSFC&&!isReactClass(a)||configuration.ignoreComponents&&isReactClass(a)),getSignature=a=>signatures.get(a),resetProxies=()=>{proxiesByID={};idsByType=new WeakMap;blackListedProxies=new WeakMap;
registeredComponents=new WeakMap;componentOptions=new WeakMap;signatures=new WeakMap;proxies=new WeakMap};resetProxies();
let tune={allowSFC:!1},_jsxFileName="~src\\errorReporter.js",lastError=[],overlayStyle={position:"fixed",left:0,top:0,right:0,backgroundColor:"rgba(255,200,200,0.9)",color:"#000",fontFamily:'-apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen", "Ubuntu", "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif',fontSize:"12px",margin:0,padding:"16px",maxHeight:"50%",overflow:"auto",zIndex:1E4},inlineErrorStyle={backgroundColor:"#FEE"},liCounter={position:"absolute",left:"10px"},listStyle=
{},EmptyErrorPlaceholder=({component:a})=>React__default.default.createElement("span",{style:inlineErrorStyle,role:"img","aria-label":"Rect-Hot-Loader Error",__self:void 0,__source:{fileName:_jsxFileName,lineNumber:46}},"\u269b\ufe0f\ud83d\udd25\ud83e\udd15 (",a?getComponentDisplayName(a.constructor||a):"Unknown location",")",a&&a.retryHotLoaderError&&React__default.default.createElement("button",{onClick:()=>a.retryHotLoaderError(),title:"Retry",__self:void 0,__source:{fileName:_jsxFileName,lineNumber:50}},
"\u27f3"));
class ErrorOverlay extends React__default.default.Component{constructor(...a){super(...a);ErrorOverlay.prototype.__init.call(this);ErrorOverlay.prototype.__init2.call(this);ErrorOverlay.prototype.__init3.call(this)}__init(){this.state={visible:!0}}__init2(){this.toggle=()=>this.setState({visible:!this.state.visible})}__init3(){this.retry=()=>this.setState(()=>{let {errors:a}=this.props;return enterHotUpdate(),clearExceptions(),a.map(({component:a})=>a).filter(Boolean).filter(({retryHotLoaderError:a})=>!!a).forEach(a=>
a.retryHotLoaderError()),{}})}render(){let {errors:a}=this.props;if(!a.length)return null;let {visible:b}=this.state;return React__default.default.createElement("div",{style:overlayStyle,__self:this,__source:{fileName:_jsxFileName,lineNumber:140}},React__default.default.createElement("h2",{style:{margin:0},__self:this,__source:{fileName:_jsxFileName,lineNumber:141}},"\u269b\ufe0f\ud83d\udd25\ud83d\ude2d: hot update was not successful ",React__default.default.createElement("button",{onClick:this.toggle,
__self:this,__source:{fileName:_jsxFileName,lineNumber:142}},b?"collapse":"expand"),React__default.default.createElement("button",{onClick:this.retry,__self:this,__source:{fileName:_jsxFileName,lineNumber:143}},"Retry")),b&&React__default.default.createElement("ul",{style:listStyle,__self:this,__source:{fileName:_jsxFileName,lineNumber:146}},a.map((b,f)=>React__default.default.createElement("li",{key:f,__self:this,__source:{fileName:_jsxFileName,lineNumber:148}},React__default.default.createElement("span",
{style:liCounter,__self:this,__source:{fileName:_jsxFileName,lineNumber:149}},"(",f+1,"/",a.length,")"),(({error:a,errorInfo:b,component:c})=>(a||(a={message:"undefined error"}),React__default.default.createElement(React__default.default.Fragment,{__self:void 0,__source:{fileName:_jsxFileName,lineNumber:78}},React__default.default.createElement("p",{style:{color:"red"},__self:void 0,__source:{fileName:_jsxFileName,lineNumber:79}},((a,b)=>a||b?React__default.default.createElement("span",{__self:void 0,
__source:{fileName:_jsxFileName,lineNumber:60}},"(",a?getComponentDisplayName(a.constructor||a):"Unknown location",a&&", ",b&&b.split("\n").filter(Boolean)[0],")"):null)(c,b&&b.componentStack)," ",a.toString?a.toString():a&&a.message||"undefined error"),b&&b.componentStack?React__default.default.createElement("div",{__self:void 0,__source:{fileName:_jsxFileName,lineNumber:84}},React__default.default.createElement("div",{__self:void 0,__source:{fileName:_jsxFileName,lineNumber:85}},"Stack trace:"),
React__default.default.createElement("ul",{style:{color:"red",marginTop:"10px"},__self:void 0,__source:{fileName:_jsxFileName,lineNumber:86}},a.stack.split("\n").slice(1,2).map((a,b)=>React__default.default.createElement("li",{key:String(b),__self:void 0,__source:{fileName:_jsxFileName,lineNumber:90}},a)),React__default.default.createElement("hr",{__self:void 0,__source:{fileName:_jsxFileName,lineNumber:91}}),b.componentStack.split("\n").filter(Boolean).map((a,b)=>React__default.default.createElement("li",
{key:String(b),__self:void 0,__source:{fileName:_jsxFileName,lineNumber:95}},a)))):a.stack&&React__default.default.createElement("div",{__self:void 0,__source:{fileName:_jsxFileName,lineNumber:100}},React__default.default.createElement("div",{__self:void 0,__source:{fileName:_jsxFileName,lineNumber:101}},"Stack trace:"),React__default.default.createElement("ul",{style:{color:"red",marginTop:"10px"},__self:void 0,__source:{fileName:_jsxFileName,lineNumber:102}},a.stack.split("\n").map((a,b)=>React__default.default.createElement("li",
{key:String(b),__self:void 0,__source:{fileName:_jsxFileName,lineNumber:103}},a)))))))(b)))))}}
let initErrorOverlay=()=>{if("undefined"!=typeof document&&document.body){var a=document.querySelector(".react-hot-loader-error-overlay");a||((a=document.createElement("div")).className="react-hot-loader-error-overlay",document.body.appendChild(a));lastError.length?ReactDOM__default.default.render(React__default.default.createElement(configuration.ErrorOverlay||ErrorOverlay,{errors:lastError,__self:void 0,__source:{fileName:_jsxFileName,lineNumber:174}}),a):a.parentNode.removeChild(a)}};
function clearExceptions(){lastError.length&&(lastError=[],initErrorOverlay())}function logException(a,b,c){console.error(a);lastError.push({error:a,errorInfo:b,component:c});initErrorOverlay()}let hotRenderWithHooks=ReactDOM__default.default.hotRenderWithHooks||((a,b)=>b());
function hydrateFiberStack(a,b){if(function(a,b){a.type=b.type;a.elementType=b.elementType||b.type;a.children=[];a.instance="function"==typeof b.type?b.stateNode:a;a.fiber=b;a.instance||(a.instance={SFC_fake:a.type,props:{},render:()=>hotRenderWithHooks(b,()=>a.type(a.instance.props))})}(b,a),a.child){({child:a}=a);do{let c={};hydrateFiberStack(a,c);b.children.push(c);a=a.sibling}while(a)}}
function hydrateLegacyStack(a,b){if(a._currentElement&&function(a,b,e){a.type=b;a.elementType=b;a.children=[];a.instance=e||a;"function"==typeof b&&b.isStatelessFunctionalProxy&&(a.instance={SFC_fake:b,props:{},render:()=>b(a.instance.props)})}(b,a._currentElement.type,a._instance||b),a._renderedComponent){let c={};hydrateLegacyStack(a._renderedComponent,c);b.children.push(c)}else a._renderedChildren&&Object.keys(a._renderedChildren).forEach(c=>{let f={};hydrateLegacyStack(a._renderedChildren[c],
f);b.children.push(f)})}let shouldNotPatchComponent=a=>isTypeBlacklisted(a);function resolveUtility(a){if("object"==typeof a){if(configuration.integratedComparator)return a;let b={type:a};if(isLazyType(b)||isMemoType(b)||isForwardType(b)||isContextType(b))return getProxyByType(a)||a}}function resolveProxy(a){if(a[PROXY_KEY])return a}function resolveNotComponent(a){if(!isCompositeComponent(a))return a}
let resolveSimpleType=a=>{if(!a)return a;var b=resolveProxy(a)||resolveUtility(a)||resolveNotComponent(a);return b||(b=getProxyByType(a))&&b.getCurrent&&b.getCurrent()||a},resolveType=(a,b={})=>a&&(resolveProxy(a)||resolveUtility(a)||resolveNotComponent(a)||function(a,b={}){var c=getProxyByType(a);shouldNotPatchComponent(a)?a=c?c.getCurrent():a:(!c&&configuration.onComponentCreate&&(configuration.onComponentCreate(a,getComponentDisplayName(a)),shouldNotPatchComponent(a))?b=a:(internalConfiguration.disableProxyCreation?
b=c:(c=a,b=getProxyByType(c)||updateProxyById("auto-"+elementCount++,c,b)),b=(a=b)?a.get():void 0),a=b);return a}(a,b))||a;function getReactStack(a){let b={};return(a=a._reactInternalFiber||a._reactInternalInstance||null)&&("number"==typeof a.tag?hydrateFiberStack(a,b):hydrateLegacyStack(a,b)),b}
let deepMarkUpdate=a=>{(({fiber:a})=>{if(a&&"string"!=typeof a.type){var b=resolveType(a.type)||a.type;a.type=b;a.expirationTime=1;a.alternate&&(a.alternate.expirationTime=1,a.alternate.type=a.type);a.memoizedProps&&"object"==typeof a.memoizedProps&&(a.memoizedProps={cacheBusterProp:!0,...a.memoizedProps});a.stateNode}})(a);a.children&&a.children.forEach(deepMarkUpdate)},renderStack=[],stackReport=()=>{let a=renderStack.slice().reverse();logger.warn("in",a[0].name,a)},emptyMap=new Map,stackContext=
()=>(renderStack[renderStack.length-1]||{}).context||emptyMap,getElementType$1=a=>a.type[UNWRAP_PROXY]?a.type[UNWRAP_PROXY]():a.type,filterNullArray=a=>a?a.filter(a=>!!a):[],unflatten=a=>a.reduce((a,c)=>(Array.isArray(c)?a.push(...unflatten(c)):a.push(c),a),[]),isArray=a=>Array.isArray(a),asArray=a=>isArray(a)?a:[a],render=(a,b)=>{return a?(a.hotComponentUpdate&&a.hotComponentUpdate(),(c=a)&&(isReactClassInstance(c)||c.SFC_fake)?a.hotComponentRender?a.hotComponentRender():a.render():isForwardType(a)?
hotRenderWithHooks(b.fiber,()=>a.type.render(a.props,null)):isArray(a)?a.map(render):a.children?a.children:[]):[];var c},NO_CHILDREN={children:[]},mapChildren=(a,b)=>({children:a.filter(a=>a).map((a,f)=>{if("object"!=typeof a||a.isMerged)return a;f=b[f]||{};var c=asArray(f.children||[]);if(Array.isArray(a))return{type:null,...mapChildren(a,c)};let d=asArray(a.props&&a.props.children||a.children||[]);return c="function"!==a.type&&c.length&&mapChildren(d,c),{nextProps:a.props,isMerged:!0,...f,...c||
{},type:a.type}})}),mergeInject=(a,b,c)=>{if(a&&!Array.isArray(a))return mergeInject([a],b);if(b&&!Array.isArray(b))return mergeInject(a,[b]);if(!a||!b)return NO_CHILDREN;if(a.length===b.length)return mapChildren(a,b);var f=filterNullArray(a);return f.length===b.length?mapChildren(f,b):(f=unflatten(f),b=unflatten(b),f.length===b.length?mapChildren(f,b):(0===b.length&&1===f.length&&"object"!=typeof f[0]||configuration.IS_REACT_MERGE_ENABLED||(logger.warn("React-hot-loader: unable to merge ",a,"and children of ",
c),stackReport()),NO_CHILDREN))},transformFlowNode=a=>a.reduce((a,c)=>{if(c&&(({type:a})=>React__default.default.Fragment&&a===React__default.default.Fragment)(c)){if(c.props&&c.props.children)return[...a,...filterNullArray(asArray(c.props.children))];if(c.children)return[...a,...filterNullArray(asArray(c.children))]}return[...a,c]},[]),scheduledUpdates=[],scheduledUpdate=0,flushScheduledUpdates=()=>{let a=scheduledUpdates;scheduledUpdates=[];scheduledUpdate=0;a.forEach(a=>{var b;if(b=a[PROXY_IS_MOUNTED]){let {updater:c,
forceUpdate:e}=a;"function"==typeof e?a.forceUpdate():c&&"function"==typeof c.enqueueForceUpdate&&c.enqueueForceUpdate(a);b=void 0}return b})},scheduleInstanceUpdate=a=>{scheduledUpdates.push(a);scheduledUpdate||(scheduledUpdate=setTimeout(flushScheduledUpdates,4))},hotReplacementRender=(a,b)=>{if(isReactClassInstance(a)){let a=getElementType$1(b);renderStack.push({name:getComponentDisplayName(a),type:a,props:b.instance.props,context:stackContext()})}try{let c=transformFlowNode(filterNullArray(asArray(render(a,
b)))),{children:f}=b;c.forEach((a,c)=>{var e=a.type;let d=f[c];if(c=b=>{let c=b.props,e={...c,...a.nextProps||{},...a.props||{}};isReactClassInstance(b)&&b.componentWillUpdate&&b.componentWillUpdate({...c},b.state);b.props=e;hotReplacementRender(b,d);b.props=c},"object"==typeof a&&d&&d.instance)if(typeof e==typeof d.elementType)if((isMemoType(a)||isLazyType(a))&&(d.children&&d.children[0]&&scheduleInstanceUpdate(d.children[0].instance),e=e.type||e),isForwardType(a))c(d.instance);else if(isContextConsumer(a))try{var g=
stackContext().get(getContextProvider(e));c({children:(a.props?a.props.children:a.children[0])(void 0!==g?g:e._currentValue)})}catch(t){}else if("function"!=typeof e){g=e?getComponentDisplayName(e):"empty";let f=stackContext();isContextProvider(a)&&(f=new Map(f),f.set(getContextProvider(e),{...a.nextProps||{},...a.props||{}}.value),g="ContextProvider");renderStack.push({name:g,type:e,props:b.instance.props,context:f});c(mergeInject(transformFlowNode(asArray(a.props?a.props.children:a.children)),d.instance.children,
d.instance));renderStack.pop()}else e===d.type?c(d.instance):(e=getElementType$1(a),isMemoType(a)&&(e=e.type||e),d.type[PROXY_KEY]||configuration.IS_REACT_MERGE_ENABLED||isTypeBlacklisted(d.type)&&logger.warn("React-hot-loader: cold element got updated ",d.type),isRegisteredComponent(e)||isRegisteredComponent(d.type)?resolveType(e)===resolveType(d.type)&&c(d.instance):areSwappable(e,d.type)?(updateProxyById(d.type[PROXY_KEY]||getIdByType(d.type),e),c(d.instance)):(logger.warn(`React-hot-loader: a ${getComponentDisplayName(e)} was found where a ${getComponentDisplayName(d)} was expected.\n          ${e}`),
stackReport())),scheduleInstanceUpdate(d.instance);else e&&d.type&&(logger.warn("React-hot-loader: got ",e,"instead of",d.type),stackReport());else d&&d.children&&d.children.length&&(logger.error("React-hot-loader: reconciliation failed","could not dive into [",a,"] while some elements are still present in the tree."),stackReport())})}catch(c){c.then||logger.warn("React-hot-loader: run time error during reconciliation",c)}isReactClassInstance(a)&&renderStack.pop()};
hotReplacementRender$1=(a,b)=>{if(!configuration.disableHotRenderer)try{internalConfiguration.disableProxyCreation=!0,renderStack=[],hotReplacementRender(a,b)}catch(c){logger.warn("React-hot-loader: reconcilation failed due to error",c)}finally{internalConfiguration.disableProxyCreation=!1}};let ERROR_STATE="react_hot_loader_catched_error",ERROR_STATE_PROTO="react_hot_loader_catched_error-prototype",OLD_RENDER="react_hot_loader_original_render";
function componentDidCatch(a,b){this[ERROR_STATE]={location:"boundary",error:a,errorInfo:b,generation:get()};Object.getPrototypeOf(this)[ERROR_STATE_PROTO]=this[ERROR_STATE];configuration.errorReporter||logException(a,b,this);this.forceUpdate()}
function componentRender(...a){let {error:b,errorInfo:c,generation:f}=this[ERROR_STATE]||{};if(b&&f===get())return React__default.default.createElement(configuration.errorReporter||EmptyErrorPlaceholder,{error:b,errorInfo:c,component:this});this.hotComponentUpdate&&this.hotComponentUpdate();try{return this[OLD_RENDER].render.call(this,...a)}catch(e){return this[ERROR_STATE]={location:"render",error:e,generation:get()},configuration.errorReporter||logException(e,void 0,this),componentRender.call(this)}}
function retryHotLoaderError(){delete this[ERROR_STATE];this.forceUpdate()}onHotComparisonOpen=()=>({});onHotComparisonElement=a=>{if(hotComparisonOpen()){if({prototype:a}=a,!a[OLD_RENDER]){let b=Object.getOwnPropertyDescriptor(a,"render");a[OLD_RENDER]={descriptor:b?b.value:void 0,render:a.render};a.componentDidCatch=componentDidCatch;a.retryHotLoaderError=retryHotLoaderError;a.render=componentRender}delete a[ERROR_STATE]}};
onHotComparisonClose=({prototype:a})=>{if(a[OLD_RENDER]){let {generation:b}=a[ERROR_STATE_PROTO]||{};b===get()||(delete a.componentDidCatch,delete a.retryHotLoaderError,a.render===componentRender?a[OLD_RENDER].descriptor?a.render=a[OLD_RENDER].descriptor:delete a.render:console.error("React-Hot-Loader: something unexpectedly mutated Component",a),delete a[ERROR_STATE_PROTO],delete a[OLD_RENDER])}};
renderOptions={componentWillRender:function(a){{var b=get();let c=a[RENDERED_GENERATION];a[RENDERED_GENERATION]=b;!internalConfiguration.disableProxyCreation&&c&&c!==b&&(enterHotUpdate(),b=getReactStack(a),hotReplacementRender$1(a,b),ReactDOM__default.default.hotCleanup&&ReactDOM__default.default.hotCleanup(),deepMarkUpdate(b))}},componentDidRender:function proxyWrapper(a){var c;if(internalConfiguration.disableProxyCreation||(c=this,scheduledUpdates=scheduledUpdates.filter(a=>a!==c)),!a)return a;
if(Array.isArray(a))return a.map(proxyWrapper);if("function"==typeof a.type){let c=getProxyByType(a.type);if(c)return{...a,type:c.get()}}return a},componentDidUpdate:a=>{a[RENDERED_GENERATION]=get();flushScheduledUpdates()}};
class AppContainer extends React__default.default.Component{static getDerivedStateFromProps(a,b){return b.generation!==get()?{error:null,generation:get()}:null}static __initStatic(){this.reactHotLoadable=!1}constructor(a){super(a);configuration.showReactDomPatchNotification&&(configuration.showReactDomPatchNotification=!1,console.warn("React-Hot-Loader: react-\ud83d\udd25-dom patch is not detected. React 16.6+ features may not work."));this.state={error:null,errorInfo:null,generation:0}}shouldComponentUpdate(a,
b){return!b.error||!this.state.error}componentDidCatch(a,b){if(logger.error(a),!hotComparisonOpen())throw this.setState({}),a;let {errorReporter:c=configuration.errorReporter}=this.props;c||logException(a,b,this);this.setState({error:a,errorInfo:b})}retryHotLoaderError(){this.setState({error:null},()=>{retryHotLoaderError.call(this)})}render(){let {error:a,errorInfo:b}=this.state,{errorReporter:c=configuration.errorReporter||EmptyErrorPlaceholder}=this.props;if(a&&this.props.errorBoundary)return React__default.default.createElement(c,
{error:a,errorInfo:b,component:this,__self:this,__source:{fileName:"~src\\AppContainer.dev.js",lineNumber:82}});if(!this.hotComponentUpdate)throw Error("React-Hot-Loader: AppContainer should be patched");return this.hotComponentUpdate(),React__default.default.Children.only(this.props.children)}}AppContainer.__initStatic();AppContainer.defaultProps={errorBoundary:!0};
let _jsxFileName$2="~src\\reconciler\\fiberUpdater.js",getLazyConstructor=a=>a._ctor?a._ctor:a._payload?a._payload._result:null,patched=a=>(a.isPatchedByReactHotLoader=!0,a),patchLazyConstructor=a=>{if(configuration.wrapLazy&&!getLazyConstructor(a).isPatchedByReactHotLoader){let b=getLazyConstructor(a);((a,b)=>{b.isPatchedByReactHotLoader=!0;a._ctor?a._ctor=b:a._payload?(a._payload._hotUpdated=!0,a._payload._result=b):console.error("could not update lazy component")})(a,()=>b().then(a=>{let b=resolveType(a.default);
return enterHotUpdate(),React__default.default.forwardRef?{default:patched(React__default.default.forwardRef(function(a,c){return React__default.default.createElement(AppContainer,{__self:this,__source:{fileName:_jsxFileName$2,lineNumber:66}},React__default.default.createElement(b,{...a,ref:c,__self:this,__source:{fileName:_jsxFileName$2,lineNumber:67}}))}))}:{default:patched(a=>React__default.default.createElement(AppContainer,{__self:void 0,__source:{fileName:_jsxFileName$2,lineNumber:55}},React__default.default.createElement(b,
{...a,__self:void 0,__source:{fileName:_jsxFileName$2,lineNumber:56}})))}}))}},updateLazy=(a,b)=>{let c=getLazyConstructor(b);getLazyConstructor(a)!==c&&c();patchLazyConstructor(a);patchLazyConstructor(b)},updateMemo=(a,{type:b})=>{a.type=resolveType(b)},updateForward=(a,{render:b})=>{a.render=b},updateContext=()=>{};
function haveEqualSignatures(a,b){try{let c=getSignature(a),f=getSignature(b);if(void 0===c&&void 0===f)return!0;if(void 0===c||void 0===f||c.key!==f.key)return!1;let e=c.getCustomHooks(),d=f.getCustomHooks();if(e.length!==d.length)return!1;for(a=0;a<d.length;a++)if(!haveEqualSignatures(e[a],d[a]))return!1}catch(c){return logger.error("React-Hot-Loader: error occurred while comparing hook signature",c),!1}return!0}
let areSignaturesCompatible=(a,b)=>!!haveEqualSignatures(a,b)||(logger.warn("\u269b\ufe0f\ud83d\udd25\ud83c\udfa3 Hook order change detected: component",a,"has been remounted"),!1),compareRegistered=(a,b)=>getIdByType(a)===getIdByType(b)&&getProxyByType(a)===getProxyByType(b)&&areSignaturesCompatible(a,b),areDeepSwappable=(a,b)=>{let c={type:a};return"function"==typeof a?areSwappable(a,b):isForwardType(c)?areDeepSwappable(a.render,b.render):!!isMemoType(c)&&areDeepSwappable(a.type,b.type)},knownPairs=
new WeakMap,emptyMap$1=new WeakMap,hotComponentCompare=(a,b,c,f)=>{let e=hotComparisonOpen(),d=a===(b=configuration.integratedResolver?resolveType(b):b);return e?isReloadableComponent(a)&&isReloadableComponent(b)&&!isColdType(a)&&!isColdType(a)&&a&&b?(d=((a,b,c,e)=>{let d=a===b;if(a&&!b||!a&&b||typeof a!=typeof b||getElementType(a)!==getElementType(b))return d;if(getIdByType(b)||getIdByType(a)){if(!compareRegistered(a,b))return!1;d=!0}return isForwardType({type:a})&&isForwardType({type:b})?!!compareRegistered(a.render,
b.render)&&(a.render===b.render||areDeepSwappable(a,b)?(c(b),!0):d):isMemoType({type:a})&&isMemoType({type:b})?!!compareRegistered(a.type,b.type)&&(a.type===b.type||areDeepSwappable(a,b)?(e?e.$$typeof===b.$$typeof?c(b):c(b.type):(logger.warn("Please update hot-loader/react-dom"),isReactClass(b.type)?c(b):c(b.type)),!0):d):isLazyType({type:a})?(updateLazy(a,b),d):isContextType({type:a})?(c(b),d):"function"==typeof b&&(d||b!==a&&areSignaturesCompatible(b,a)&&areSwappable(b,a))?((e=(e=b[UNWRAP_PROXY])&&
getProxyByType(e()))?(e.dereference(),a=a[PROXY_KEY]||getIdByType(a),b=(c=b[UNWRAP_PROXY])?c():b,updateProxyById(a,b)):c(b),!0):d})(a,b,c,f),(c=knownPairs.get(a)||new WeakMap).set(b,d),knownPairs.set(a,c),d):d:((c=d)||(c=(knownPairs.get(a)||emptyMap$1).get(b)),c||!1)},forceSimpleSFC={proxy:{pureSFC:!0}},hookWrapper=a=>{let b=function(b,f){if(configuration.reloadHooks&&f){const c=[...f];return configuration.reloadHooksOnBodyChange&&c.push(String(b)),(0<f.length||configuration.reloadLifeCycleHooks&&
0===f.length)&&c.push(getHotGeneration()),a(b,c)}return a(b,f)};return b.isPatchedByReactHotLoader=!0,b},noDeps=()=>[],reactHotLoader={signature:(a,b,c=noDeps)=>(signatures.set(a,{key:b,getCustomHooks:c}),a),register(a,b,c,f={}){let e=`${c}#${b}`;if(isCompositeComponent(a)&&"string"==typeof b&&b&&"string"==typeof c&&c){let d=getProxyById(e);d&&d.getCurrent()!==a&&(configuration.IS_REACT_MERGE_ENABLED||(isTypeBlacklisted(a)||isTypeBlacklisted(d.getCurrent()))&&logger.error("React-hot-loader: Cold component",
b,"at",c,"has been updated"));configuration.onComponentRegister&&configuration.onComponentRegister(a,b,c);configuration.onComponentCreate&&configuration.onComponentCreate(a,getComponentDisplayName(a));registerComponent(updateProxyById(e,a,f).get());registerComponent(a);increment()}isContextType({type:a})&&(["Provider","Consumer"].forEach(b=>{let c=Object.getOwnPropertyDescriptor(a,b);c&&c.value&&updateFunctionProxyById(`${e}:${b}`,c.value,updateContext)}),updateFunctionProxyById(e,a,updateContext),
increment());isLazyType({type:a})&&(updateFunctionProxyById(e,a,updateLazy),increment());isForwardType({type:a})&&(reactHotLoader.register(a.render,`${b}:render`,c,forceSimpleSFC),updateFunctionProxyById(e,a,updateForward),increment());isMemoType({type:a})&&(reactHotLoader.register(a.type,`${b}:memo`,c,forceSimpleSFC),updateFunctionProxyById(e,a,updateMemo),increment())},reset(){resetProxies()},preact(a){((a,c)=>{let b=a.options.vnode;setConfiguration(tune);a.options.vnode=a=>{a.type?a.type=c(a.type):
a.nodeName&&(a.nodeName=c(a.nodeName));b&&b(a)}})(a,resolveType)},resolveType:a=>resolveType(a),patch(a,b){let c=resolveType;if(b&&!b.render&&logger.error("React-Hot-Loader: broken state detected, please import React-Hot-Loader before react-dom, see https://github.com/gaearon/react-hot-loader/issues/1315"),b&&b.setHotElementComparator&&(b.setHotElementComparator(hotComponentCompare),configuration.disableHotRenderer=configuration.disableHotRendererWhenInjected,configuration.ignoreSFC=configuration.ignoreSFCWhenInjected,
configuration.IS_REACT_MERGE_ENABLED=!0,configuration.showReactDomPatchNotification=!1,configuration.integratedComparator=!0,b.setHotTypeResolver&&(configuration.integratedResolver=!0,c=resolveSimpleType,b.setHotTypeResolver(resolveType))),!a.createElement.isPatchedByReactHotLoader){let b=a.createElement;a.createElement=(a,...d)=>b(c(a),...d);a.createElement.isPatchedByReactHotLoader=!0}if(!a.cloneElement.isPatchedByReactHotLoader){let b=a.cloneElement;a.cloneElement=(a,...d)=>{let e=a.type&&c(a.type);
return e&&e!==a.type?b({...a,type:e},...d):b(a,...d)};a.cloneElement.isPatchedByReactHotLoader=!0}if(a.createFactory.isPatchedByReactHotLoader||(a.createFactory=b=>{let c=a.createElement.bind(null,b);return c.type=b,c},a.createFactory.isPatchedByReactHotLoader=!0),!a.Children.only.isPatchedByReactHotLoader){let b=a.Children.only;a.Children.only=a=>b({...a,type:c(a.type)});a.Children.only.isPatchedByReactHotLoader=!0}if(a.useEffect&&!a.useEffect.isPatchedByReactHotLoader){a.useEffect=hookWrapper(a.useEffect);
a.useLayoutEffect=hookWrapper(a.useLayoutEffect);a.useCallback=hookWrapper(a.useCallback);a.useMemo=hookWrapper(a.useMemo);let {useContext:b}=a;a.useContext=(a,...d)=>b(c(a),...d)}}},openedModules={},lastModuleOpened="",hotModules={},hotModule=a=>(hotModules[a]||(hotModules[a]={instances:[],updateTimeout:0}),hotModules[a]),createQueue=(a=a=>a())=>{let b,c=[],f=()=>{c.forEach(a=>a());c=[]};return e=>(0===c.length&&(b=Promise.resolve().then(()=>a(f))),c.push(e),b)},requireIndirect="undefined"!=typeof __webpack_require__?
__webpack_require__:require,runInRequireQueue=createQueue(),runInRenderQueue=createQueue(a=>{ReactDOM__default.default.unstable_batchedUpdates?ReactDOM__default.default.unstable_batchedUpdates(a):a()});reactHotLoader.register(AppContainer,"AppContainer","hot-dev");let getProxyOrType=a=>{let b=getProxyByType(a);return b?b.get():a};reactHotLoader.patch(React__default.default,ReactDOM__default.default);
let peq=new Uint32Array(65536),distance=(a,b)=>(a.length<b.length&&([b,a]=[a,b]),0===b.length?a.length:32>=a.length?((a,b)=>{let c=a.length,d=b.length,f=1<<c-1,h=-1,g=0,t=c,m=c;for(;m--;)peq[a.charCodeAt(m)]|=1<<m;for(m=0;m<d;m++){let a=peq[b.charCodeAt(m)],c=a|g;a|=(a&h)+h^h;g|=~(a|h);h&=a;g&f&&t++;h&f&&t--;g=g<<1|1;h=h<<1|~(c|g);g&=c}for(m=c;m--;)peq[a.charCodeAt(m)]=0;return t})(a,b):((a,b)=>{var c,d,f;let h=b.length,g=a.length,t=[],m=[];var n=Math.ceil(h/32);var r=Math.ceil(g/32);for(c=0;c<n;c++)m[c]=
-1,t[c]=0;for(n=0;n<r-1;n++){var k=0;var p=-1;var u=32*n;c=Math.min(32,g)+u;for(d=u;d<c;d++)peq[a.charCodeAt(d)]|=1<<d;for(d=0;d<h;d++){var w=peq[b.charCodeAt(d)];var v=m[d/32|0]>>>d%32&1;var x=w|k;k|=~((w=((w|(f=t[d/32|0]>>>d%32&1))&p)+p^p|w|f)|p);p&=w;k>>>31^v&&(m[d/32|0]^=1<<d%32);p>>>31^f&&(t[d/32|0]^=1<<d%32);p=p<<1|f;p|=~(x|(k=k<<1|v));k&=x}for(;u<c;u++)peq[a.charCodeAt(u)]=0}p=0;c=-1;n*=32;r=Math.min(32,g-n)+n;for(u=n;u<r;u++)peq[a.charCodeAt(u)]|=1<<u;u=g;for(d=0;d<h;d++)k=peq[b.charCodeAt(d)],
v=m[d/32|0]>>>d%32&1,x=k|p,u+=(p|=~((k=((k|(f=t[d/32|0]>>>d%32&1))&c)+c^c|k|f)|c))>>>g%32-1&1,u-=(c&=k)>>>g%32-1&1,p>>>31^v&&(m[d/32|0]^=1<<d%32),c>>>31^f&&(t[d/32|0]^=1<<d%32),c=c<<1|f,c|=~(x|(p=p<<1|v)),p&=x;for(b=n;b<r;b++)peq[a.charCodeAt(b)]=0;return u})(a,b));exports.AppContainer=AppContainer;exports.areComponentsEqual=(a,b)=>getProxyOrType(a)===getProxyOrType(b);exports.cold=a=>(blackListedProxies.set(a,!0),a);exports.compareOrSwap=(a,b)=>hotComponentCompare(a,b);
exports.configureComponent=(a,b)=>componentOptions.set(a,b);exports.default=reactHotLoader;exports.enterModule=a=>{a&&a.id?(lastModuleOpened=a.id,openedModules[a.id]=!0):logger.warn("React-hot-loader: no `module` variable found. Did you shadow a system variable?")};exports.hoistNonReactStatic=hoistNonReactStatic;
exports.hot=a=>{if(!a)throw Error("React-hot-loader: `hot` was called without any argument provided");let b=a.id||a.i||a.filename;if(!b)throw console.error("`module` provided",a),Error("React-hot-loader: `hot` could not find the `name` of the the `module` you have provided");let c=hotModule(b);((a,b)=>{let c=a=>{if(a&&a instanceof Error)return void console.error(a);let c=hotModule(b),d=()=>{runInRenderQueue(()=>{enterHotUpdate();const a=getHotGeneration();if(c.instances.forEach(a=>a.forceUpdate()),
configuration.trackTailUpdates){let b=0;const c=()=>{setTimeout(()=>{getHotGeneration()!==a?(logger.warn("React-Hot-Loader: some components were updated out-of-bound. Updating your app to reconcile the changes."),increment(),d()):5>++b&&c()},16)};c()}})};runInRequireQueue(()=>{try{requireIndirect(b)}catch(n){console.error("React-Hot-Loader: error detected while loading",b),console.error(n)}}).then(d)};a.hot?(a.hot.accept(c),a.hot.addStatusHandler&&"idle"===a.hot.status()&&a.hot.addStatusHandler(a=>
{"apply"===a&&(clearExceptions(),c())})):logger.warn("React-hot-loader: Hot Module Replacement is not enabled")})(a,b);clearExceptions();let f=(a=>setTimeout(()=>{let b=`hot update failed for module "${a}". Last file processed: "${lastModuleOpened}".`;logger.error(b);logException({toString:()=>b})},100))(b),e=!1;return(d,l)=>{var h;return clearTimeout(f),e||(e=!0,reactHotLoader.register(d,getComponentDisplayName(d),`RHL${b}`)),hoistNonReactStatic(h=class extends React.Component{componentDidMount(){c.instances.push(this)}componentWillUnmount(){if(a&&
openedModules[a.id]){let a=getComponentDisplayName(d);logger.error(`React-hot-loader: Detected AppContainer unmount on module '${b}' update.\nDid you use "hot(${a})" and "ReactDOM.render()" in the same file?\n"hot(${a})" shall only be used as export.\nPlease refer to "Getting Started" (https://github.com/gaearon/react-hot-loader/).`)}c.instances=c.instances.filter(a=>a!==this)}render(){return React__default.default.createElement(AppContainer,{...l,__self:this,__source:{fileName:"~src\\hot.dev.js",
lineNumber:170}},React__default.default.createElement(d,{...this.props,__self:this,__source:{fileName:"~src\\hot.dev.js",lineNumber:171}}))}},d),h.displayName=`HotExported${getComponentDisplayName(d)}`,h}};exports.leaveModule=a=>{a&&a.id&&delete openedModules[a.id]};exports.setConfig=a=>setConfiguration(a)
